version: '2'

networks:

  chain-net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
services:

# Blockchain
  bootstrap:
    image: ethereum/client-go:v1.10.7
    restart: on-failure
    container_name: bootstrap
    hostname: bootstrap
    links:
      - blockscout
    command: '--datadir=~/.ethereum/devchain --nodekeyhex=091bd6067cb4612df85d9c1ff85cc47f259ced4d4cd99816b14f35650f59c322 --networkid=456719 --http --http.addr 0.0.0.0 --port 30303 --http.port 8545 --http.api debug,net,eth,shh,web3,txpool --ws.api "eth,net,web3,network,debug,txpool" --ws --ws.addr 0.0.0.0 --ws.port 8546 --ws.origins "*" --http.vhosts "*" --syncmode "full" --nat extip:172.16.238.2'
    volumes:
      - ./config/data/password:/root/files/password:ro
      - ./config/genesis.json:/root/files/genesis.json:ro
      - ./config/data/keystore:/root/.ethereum/devchain/keystore:rw
      - ./config/data/peers.json:/root/.ethereum/devchain/static-nodes.json:ro
      - ./blockchain/bootstrap-data:/root/.ethereum:rw
      - /etc/localtime:/etc/localtime:ro
    networks:
      chain-net:
        ipv4_address: 172.16.238.2
  eth:
    image: ethereum/client-go:v1.10.7
    restart: on-failure
    links:
      - bootstrap
    volumes:
      - ./config/data/password:/root/files/password:ro
      - ./config/genesis.json:/root/files/genesis.json:ro
      - ./config/data/keystore:/root/.ethereum/devchain/keystore:rw
      - /etc/localtime:/etc/localtime:ro
      - ./blockchain/node-data:/root/.ethereum:rw
    command: '--datadir=~/.ethereum/devchain --networkid=456719 --bootnodes="enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@172.16.238.2:30303" --preload loadscript.js --nat extip:172.16.238.3'
    networks:
      chain-net:
        ipv4_address: 172.16.238.3

  miner:
    image: ethereum/client-go:v1.10.7
    restart: on-failure
    links:
      - bootstrap
    container_name: miner
    command: '--unlock 0x007ccffb7916f37f7aeef05e8096ecfbe55afc2f --datadir=~/.ethereum/devchain --networkid=456719 --bootnodes="enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@172.16.238.2:30303" --password /root/files/password/pass.txt --mine --nat extip:172.16.238.4'
    volumes:
      - ./config/data/password:/root/files/password:ro
      - ./config/genesis.json:/root/files/genesis.json:ro
      - ./config/data/keystore:/root/.ethereum/devchain/keystore:rw
      - /etc/localtime:/etc/localtime:ro
      - ./blockchain/miner-data:/root/.ethereum:rw
    networks:
      chain-net:
        ipv4_address: 172.16.238.4

# Dashboard
  redis_db:
    image: 'redis:alpine'
    ports:
      - 6379:6379
    container_name: redis_db
    command: redis-server
    volumes:
      - ./redis-data:/data
    networks:
      chain-net:
        ipv4_address: 172.16.238.5

  db:
    image: postgres:14
    restart: always
    container_name: 'postgres'
    environment:
        POSTGRES_PASSWORD: ''
        POSTGRES_USER: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 7432:5432
    networks:
      chain-net:
        ipv4_address: 172.16.238.6

  blockscout:
    depends_on:
      - db
      - smart-contract-verifier
      - redis_db
    image: blockscout/blockscout:4.1.7
    restart: always
    container_name: 'blockscout'
    links:
      - db:database
    command: bash -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ./config/blockscout/common-blockscout.env
    networks:
      chain-net:
        ipv4_address: 172.16.238.8
    environment:
        ETHEREUM_JSONRPC_VARIANT: 'geth'
        BLOCK_TRANSFORMER: 'clique'
        ETHEREUM_JSONRPC_HTTP_URL: http://172.16.238.2:8545
        DATABASE_URL: postgresql://postgres:@host.docker.internal:7432/blockscout?ssl=false
        ECTO_USE_SSL: 'false'
        SECRET_KEY_BASE: '56NtB48ear7+wMSf0IQuWDAAazhpb31qyc7GiyspBP2vh7t5zlCsF5QDv76chXeN'
    ports:
      - 4000:4000

  smart-contract-verifier:
    image: ghcr.io/blockscout/smart-contract-verifier:v0.5.0
    restart: always
    container_name: 'smart-contract-verifier'
    env_file:
      -  ./config/blockscout/common-smart-contract-verifier.env
    ports:
      - 8043:8043
    networks:
      chain-net:
        ipv4_address: 172.16.238.10
