

version: '3.8'

networks:
# Define the network for the containers
  priv-eth-net:
    driver: bridge
    # Set container to connect to the host through a bridge to localhost
    ipam:
      config:
      # Define the subnet for the network which allows limiting maximum capacity
      - subnet: 255.255.255.248/27

services:

# Ethereum Network

  geth-bootnode: # Boots the blockchain
    hostname: geth-bootnode
    container_name: bootNode
    restart: on-failure
    env_file:
      - blockchain-docker/config/.env
    build: blockchain-docker
    command:
      # --networkid=314159
      #      --netrestrict "255.255.255.248/28"
      # --nat extip:"255.255.255.242"
      # --port 30301
      #   --syncmode "full"
      #--ipcdisable
      #--maxpeers 3
     --allow-insecure-unlock
     --nodekey /root/nodekeys/bootnode.txt 
     --config /root/bootnode.toml
    networks:
      priv-eth-net:
        ipv4_address: "255.255.255.242"
    ports:
      - "30301:30301"
      - "30301:30301/udp"

  geth-rpc-endpoint: # Interacts with the frontend (API Gateway)
    hostname: geth-rpc-endpoint
    container_name: rpcNode
    restart: on-failure
    env_file:
      - blockchain-docker/config/.env
    build: blockchain-docker

    depends_on:
      - geth-bootnode    
    command: 
      --bootnodes "enode://43974299a4c52b220d8eed430a7ed1479f29548041e3ca67ddc1a4886835878c174d45dfd9e73ebd4901e8071c5bb19003f52e4e408e8ec5ce350f8f74a335a8@255.255.255.242:30301"
      --allow-insecure-unlock
      --http
      --http.api admin,debug,web3,eth,txpool,personal,clique,miner,net
      --http.addr 0.0.0.0
      --http.vhosts "*"
      --http.port 8545
      --netrestrict="255.255.255.248/28"
      --ws
      --ws.origins '*' 
      --ws.port 8546
      --ws.addr 0.0.0.0
      --ws.api "admin,debug,web3,eth,txpool,personal,clique,miner,net" 
      --syncmode "full"
      --gcmode "archive"
      --txlookuplimit 0 
      --nodekey=/root/nodekeys/rpc.txt
      --port 30304
      --nat extip:"255.255.255.243"
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30304:30304"
      - "30304:30304/udp"
    networks:
      priv-eth-net:
        ipv4_address: "255.255.255.243"
    volumes:
      - ./blockchain-docker/blockchain-data/backups:/root/backups
  geth-signer: # Signs/Mines transactions
    hostname: geth-signer
    container_name: minerNode
    env_file:
      - blockchain-docker/config/.env
    build: blockchain-docker
    depends_on:
      - geth-bootnode
      - geth-rpc-endpoint
    command:
      --bootnodes "enode://43974299a4c52b220d8eed430a7ed1479f29548041e3ca67ddc1a4886835878c174d45dfd9e73ebd4901e8071c5bb19003f52e4e408e8ec5ce350f8f74a335a8@255.255.255.242:30301, enode://8a9f6e0f6e579e2eda70f8022021ecace552268db2eb6f9cd2fd29aee9d3a2e2c6a622fe6fefa83f41cd5a9fbf85b9b7e7ff696c3df72443b258a0cf51086555@255.255.255.243:30304"
      --nodekey=/root/nodekeys/miner.txt
      --unlock 0x3bcf84dd3ee4c8e3d99bdf37a6ce32a7562c93bf
      --mine
      --password /root/.ethereum/password.txt
      --netrestrict="255.255.255.248/28"
      --port 30305
      --nat extip:"255.255.255.244"
    networks:
      priv-eth-net:
        ipv4_address: "255.255.255.244"
    volumes:
      - ./blockchain-docker/blockchain-data/backups:/root/backups
    ports:
    - "30305:30305"
    - "30305:30305/udp"
  geth-signer-2: # Signs/Mines Transactions
    hostname: geth-signer2
    container_name: minerNode2
    env_file:
      - blockchain-docker/config/.env
    build: blockchain-docker
    depends_on:
      - geth-bootnode
      - geth-rpc-endpoint
      - geth-signer
      - blockscout
    command:
      # Statically connect other nodes
      --bootnodes "enode://43974299a4c52b220d8eed430a7ed1479f29548041e3ca67ddc1a4886835878c174d45dfd9e73ebd4901e8071c5bb19003f52e4e408e8ec5ce350f8f74a335a8@255.255.255.242:30301, enode://32550d2084b947c7dd7500f8f0e2dc47b8ca5cdab07a56c3535c24624767f12bbd37b4e6eca391f406debebede289c7403c675f7c3143243419e82fc39778899@255.255.255.244:30305, enode://8a9f6e0f6e579e2eda70f8022021ecace552268db2eb6f9cd2fd29aee9d3a2e2c6a622fe6fefa83f41cd5a9fbf85b9b7e7ff696c3df72443b258a0cf51086555@255.255.255.243:30304"
      --unlock 0xe1f5c19a40c4cc55dd5b98116a05d342da9064b3
      --nodekey /root/nodekeys/miner2.txt
      --mine
      --miner.etherbase 0xe1f5c19a40c4cc55dd5b98116a05d342da9064b3
      --password /root/.ethereum/password.txt
      --netrestrict="255.255.255.248/28"
      --port 30306
      --nat extip:"255.255.255.245"
    ports:
      - "30306:30306"
      - "30306:30306/udp"
    networks:
      priv-eth-net:
        ipv4_address: "255.255.255.245"
    volumes:
      - ./blockchain-docker/blockchain-data/backups:/root/backups



# Blockscout
  

  redis_db:
    image: 'redis:alpine'
    ports:
      - 6379:6379
    container_name: redis-blkscout
    command: redis-server
    networks:
    - priv-eth-net
   # volumes:
   #   - ./redis-data:/data

  db:
    image: postgres:14
    restart: always
    container_name: postgres-blkscout
    environment:
        POSTGRES_PASSWORD: ''
        POSTGRES_USER: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
   # volumes:
    #  - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 7432:5432
    networks:
    - priv-eth-net

  blockscout:
    depends_on:
      - db
      - smart-contract-verifier
      - redis_db
      - geth-rpc-endpoint
    image: blockscout/blockscout:4.1.8
    restart: always
    container_name: 'blkscout'
    links:
      - db:database
    command: bash -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ./envs/common-blockscout.env
    networks:
        - priv-eth-net
    environment:
        ETHEREUM_JSONRPC_VARIANT: 'geth'
        BLOCK_TRANSFORMER: 'clique'
        ETHEREUM_JSONRPC_HTTP_URL: http://host.docker.internal:8545/
        DATABASE_URL: postgresql://postgres:@host.docker.internal:7432/blockscout?ssl=false
        ECTO_USE_SSL: 'false'
        SECRET_KEY_BASE: '56NtB48ear7+wMSf0IQuWDAAazhpb31qyc7GiyspBP2vh7t5zlCsF5QDv76chXeN'
    ports:
      - 4000:4000
    # volumes:
#   - ./logs/:/app/logs/

  smart-contract-verifier:
    image: ghcr.io/blockscout/smart-contract-verifier:${SMART_CONTRACT_VERIFIER_DOCKER_TAG:-latest}
    restart: always
    container_name: 'smart-contract-verifier'
    env_file:
      -  ./envs/common-smart-contract-verifier.env
    ports:
      - 8043:8043
    networks:
    - priv-eth-net

# Graph Node
  graph-node:
    image: graphprotocol/graph-node
    container_name: Graph-Node
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - ipfs
      - postgres
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: 'attackchain:http://host.docker.internal:8545'
      GRAPH_LOG: info
  ipfs:
    container_name: IPFS
    image: ipfs/go-ipfs:v0.10.0
    ports:
      - '5001:5001'
    volumes:
      - ./data/ipfs:/data/ipfs
  postgres:
    image: postgres
    container_name: Graph-DB
    ports:
      - '5432:5432'
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements"
      ]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
      # FIXME: remove this env. var. which we shouldn't need. Introduced by
      # <https://github.com/graphprotocol/graph-node/pull/3511>, maybe as a
      # workaround for https://github.com/docker/for-mac/issues/6270?
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
